version: '3.8'

services:
  web:
    image: laszlolaszlo/django_base:latest
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --reload --timeout=5 --threads=10 --workers=1
    volumes:
      - ./:/home/app/web/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev